# Generated by Django 5.2.1 on 2025-05-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0005_alter_order_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temp_order_id",
                    models.CharField(
                        default="",
                        help_text="PayPal payment ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        help_text="PayPal payment ID", max_length=255, unique=True
                    ),
                ),
                (
                    "payer_id",
                    models.CharField(
                        blank=True,
                        help_text="PayPal payer ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayPalPaymentEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lfs_paypal.paypalpayment",
                    ),
                ),
            ],
        ),
    ]
