# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 08:20
from __future__ import unicode_literals

from django.db import migrations


def update_price_calculator(apps, schema_editor):
    PaymentMethod = apps.get_model("payment", "PaymentMethod")
    for payment_method in PaymentMethod.objects.all():
        if payment_method.module == "lfs_paypal.PayPalProcessor":
            payment_method.module = "lfs_paypal.processor.PayPalProcessor"
        payment_method.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lfs_paypal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_price_calculator),
    ]
