# Generated by Django 5.1.5 on 2025-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lfs_paypal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paypalpaymententry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("approved", "Approved"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
